#!/bin/bash
#Script Variables
HOST='209.159.152.66';
USER='crypticv_socagi';
PASS='@@@@F1r3n3t';
DBNAME='crypticv_socagi';
PORT_TCP='1194';
PORT_UDP='53';
API_LINK='https://socagivpn.xyz/api/authentication';
API_KEY='FIRENET';
DNS_DOMAIN='';
DNS_ZONE='';
DNS_GLOBAL='';
DNS_EMAIL='';
404: Not Found